security:
    encoders:
        VLA\vivelaaventuraBundle\Entity\Usuarios:
            algorithm: md5
            encode_as_base64: false
            iterations: 0

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER: [ROLE_ADMIN]

    providers:
        user_db:
            entity: { class: VLA\vivelaaventuraBundle\Entity\Usuarios, property: usuario }

    firewalls:
        main:
            pattern: /admin/.*
            provider: user_db
            form_login:
                check_path: /admin/login_check
                login_path: /admin
                remember_me: true
                always_use_default_target_path: false
                default_target_path: /admin/gestion
                target_path_parameter: _target_path
                use_referer: false
            logout:
                path: /admin/logout
                target: /
            remember_me:
                key: vive_la_aventura_o_vive_la_vida
                lifetime: 3600
                path: /admin/.*
                domain: ~
            security: true
            anonymous: true

    access_control:
        - { path: /admin/*, roles: ROLE_USER }

